version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3001:3001"

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "3000:3000"